name: Publish Docker Image

on:
  release:
    types: [released]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/healthcheck-tester:${{ github.event.release.tag_name }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/healthcheck-tester:${{ github.event.release.tag_name }} ${{ secrets.DOCKERHUB_USERNAME }}/healthcheck-tester:latest

      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/healthcheck-tester:${{ github.event.release.tag_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/healthcheck-tester:latest
